spring:
  application:
    name: switch-monitor
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/switch_db
    username: switch_user
    password: switch_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: switch-monitor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: localhost
      port: 16379

server:
  port: 8080
